#!/bin/zsh
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
rm -f *.log
${DIR}/code/sim -bs 16 -us 8192 -a 1 -wb -wa traces/public-block.trace > public-block1.log
${DIR}/code/sim -bs 16 -us 8192 -a 1 -wb -wa traces/public-assoc.trace > public-assoc1.log
${DIR}/code/sim -bs 16 -us 8192 -a 1 -wb -wa traces/public-write.trace > public-write1.log
${DIR}/code/sim -bs 16 -us 8192 -a 1 -wb -wa traces/public-instr.trace > public-instr1.log

${DIR}/code/sim -bs 16 -us 8192 -a 1 -wb -wa traces/spice10.trace > spice10.log
${DIR}/code/sim -bs 16 -us 8192 -a 1 -wb -wa traces/spice100.trace > spice100.log
${DIR}/code/sim -bs 16 -us 8192 -a 1 -wb -wa traces/spice1000.trace > spice1000.log

${DIR}/code/sim -bs 16 -us 8192 -a 1 -wb -wa ext_traces/spice.trace > spice.log
